using System.Text;
using System.Xml.Linq;

namespace ImagesResxToAvalonia;

public static class ImagesGenerator
{
    private const string FileReferenceType = "System.Resources.ResXFileRef, System.Windows.Forms";

    public static string Generate(string resxPath)
    {
        string fullResxPath = Path.GetFullPath(resxPath);
        XDocument document = XDocument.Load(fullResxPath, LoadOptions.PreserveWhitespace);
        string resxDirectory = Path.GetDirectoryName(fullResxPath)!;
        List<ImageResourceEntry> entries = [];

        foreach (XElement dataElement in document.Root?.Elements("data") ?? [])
        {
            if (!string.Equals((string?)dataElement.Attribute("type"), FileReferenceType, StringComparison.Ordinal))
            {
                continue;
            }

            string propertyName = (string?)dataElement.Attribute("name")
                ?? throw new InvalidDataException("Images.resx contains a file reference without a name.");
            string value = dataElement.Element("value")?.Value
                ?? throw new InvalidDataException($"Images.resx entry '{propertyName}' has no value.");
            string sourcePath = value.Split(';', count: 2)[0]
                .Replace('\\', Path.DirectorySeparatorChar)
                .Replace('/', Path.DirectorySeparatorChar);
            string fullSourcePath = Path.GetFullPath(sourcePath, resxDirectory);
            if (!File.Exists(fullSourcePath))
            {
                throw new InvalidDataException($"Images.resx entry '{propertyName}' points to missing file '{sourcePath}'.");
            }

            entries.Add(new ImageResourceEntry(propertyName, GetAvaloniaResourcePath(fullSourcePath)));
        }

        if (entries.Count == 0)
        {
            throw new InvalidDataException("Images.resx contains no file-backed image entries.");
        }

        StringBuilder builder = new();
        AppendLine("// <auto-generated />");
        AppendLine("// Generated by eng/tools/ImagesResxToAvalonia from GitUI/Properties/Images.resx.");
        AppendLine();
        AppendLine("using System.Collections.Concurrent;");
        AppendLine("using Avalonia.Controls;");
        AppendLine("using Avalonia.Media.Imaging;");
        AppendLine("using Avalonia.Platform;");
        AppendLine();
        AppendLine("namespace GitUI.Properties;");
        AppendLine();
        AppendLine("/// <summary>");
        AppendLine("/// Provides the original GitUI image-resource property names as cached Avalonia bitmaps.");
        AppendLine("/// </summary>");
        AppendLine("public static class Images");
        AppendLine("{");
        AppendLine("    private static readonly ConcurrentDictionary<string, Lazy<Bitmap>> _cache = new(StringComparer.Ordinal);");
        AppendLine("    private static readonly Lazy<WindowIcon> _applicationIcon = new(CreateApplicationIcon, LazyThreadSafetyMode.ExecutionAndPublication);");
        AppendLine("    private static readonly IReadOnlyDictionary<string, string> _resourcePaths =");
        AppendLine("        new Dictionary<string, string>(StringComparer.Ordinal)");
        AppendLine("        {");

        foreach (ImageResourceEntry entry in entries)
        {
            AppendLine($"            [nameof({entry.PropertyName})] = \"{EscapeString(entry.ResourcePath)}\",");
        }

        AppendLine("        };");
        AppendLine();
        AppendLine("    internal static IReadOnlyDictionary<string, string> ResourcePaths => _resourcePaths;");
        AppendLine();
        AppendLine("    public static WindowIcon ApplicationIcon => _applicationIcon.Value;");

        foreach (ImageResourceEntry entry in entries)
        {
            AppendLine();
            AppendLine($"    public static Bitmap {entry.PropertyName} => Get(nameof({entry.PropertyName}));");
        }

        AppendLine();
        AppendLine("    private static Bitmap Get(string name)");
        AppendLine("    {");
        AppendLine("        string resourcePath = _resourcePaths[name];");
        AppendLine("        return _cache.GetOrAdd(");
        AppendLine("            resourcePath,");
        AppendLine("            static path => new Lazy<Bitmap>(");
        AppendLine("                () =>");
        AppendLine("                {");
        AppendLine("                    using Stream stream = AssetLoader.Open(new Uri(\"avares://GitUI.Avalonia/\" + path));");
        AppendLine("                    return new Bitmap(stream);");
        AppendLine("                },");
        AppendLine("                LazyThreadSafetyMode.ExecutionAndPublication)).Value;");
        AppendLine("    }");
        AppendLine();
        AppendLine("    private static WindowIcon CreateApplicationIcon()");
        AppendLine("    {");
        AppendLine("        using Stream stream = AssetLoader.Open(new Uri(\"avares://GitUI.Avalonia/\" + _resourcePaths[nameof(GitExtensionsLogo256)]));");
        AppendLine("        return new WindowIcon(stream);");
        AppendLine("    }");
        AppendLine("}");

        return builder.ToString();

        void AppendLine(string value = "")
        {
            builder.Append(value);
            builder.Append('\n');
        }
    }

    private static string GetAvaloniaResourcePath(string fullSourcePath)
    {
        string normalizedPath = fullSourcePath.Replace('\\', '/');
        const string gitUiResourcesSegment = "/src/app/GitUI/Resources/";
        int resourcesIndex = normalizedPath.IndexOf(gitUiResourcesSegment, StringComparison.Ordinal);
        if (resourcesIndex >= 0)
        {
            return "Resources/" + normalizedPath[(resourcesIndex + gitUiResourcesSegment.Length)..];
        }

        const string logoSegment = "/setup/assets/Logo/";
        int logoIndex = normalizedPath.IndexOf(logoSegment, StringComparison.Ordinal);
        if (logoIndex >= 0)
        {
            return "Resources/Logo/" + normalizedPath[(logoIndex + logoSegment.Length)..];
        }

        throw new InvalidDataException($"Image source is outside GitUI Resources and setup/assets/Logo: '{fullSourcePath}'.");
    }

    private static string EscapeString(string value)
        => value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal);

    private sealed record ImageResourceEntry(string PropertyName, string ResourcePath);
}
