using Avalonia.Controls;
using Avalonia.Input;
using Avalonia.Media;
using GitUI.Compat;
using Keys = GitExtensions.Shims.WinForms.Keys;

namespace GitUI.CommandsDialogs.BrowseDialog;

/// <summary>
/// Represents a menu command with Text, ShortcutKey or ShortcutDisplayString, Action,
/// Icon and optionally CheckBoxes.
/// From a MenuCommand a (theoretically) unlimited number of actual MenuItems can
/// be created that all behave the same.
/// A MenuCommand can also be a separator
///
/// Purpose: have methods from specific context menus also available in main menu.
/// </summary>
internal sealed class MenuCommand
{
    public static MenuCommand CreateSeparator()
    {
        return new MenuCommand { IsSeparator = true };
    }

    public static MenuCommand CreateGroupHeader(string text)
    {
        return new MenuCommand
        {
            IsGroupHeader = true,
            Name = text.Replace(' ', '_') + "ToolStripMenuItem",
            Text = text,
        };
    }

    public static Control CreateToolStripItem(MenuCommand menuCommand)
    {
        if (menuCommand.IsSeparator)
        {
            return new Separator();
        }

        if (menuCommand.IsGroupHeader)
        {
            MenuItem headerToolStripMenuItem = new()
            {
                Name = menuCommand.Name,
                Header = AvaloniaTranslationUtils.ToAvaloniaMnemonics(menuCommand.Text ?? string.Empty),
                IsEnabled = false,
            };
            UserControls.RevisionGrid.MenuUtil.SetAsCaptionMenuItem(headerToolStripMenuItem);

            return headerToolStripMenuItem;
        }

        MenuItem toolStripMenuItem = new()
        {
            Name = menuCommand.Name,
            Tag = menuCommand.Name,
            Header = AvaloniaTranslationUtils.ToAvaloniaMnemonics(menuCommand.Text ?? string.Empty),
            Icon = CreateIcon(menuCommand.Image),
            InputGesture = ParseShortcut(menuCommand.ShortcutKeyDisplayString),
        };
        ToolTip.SetTip(toolStripMenuItem, menuCommand.ToolTipText);

        toolStripMenuItem.Click += (obj, sender) =>
        {
            if (menuCommand.ExecuteAction is not null)
            {
                menuCommand.ExecuteAction();
            }
            else
            {
                MessageBoxes.Show("No ExecuteAction assigned to this MenuCommand. Please submit a bug report.", TranslatedStrings.Error, MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        };

        return toolStripMenuItem;
    }

    private readonly List<MenuItem> _registeredMenuItems = [];

    /// <summary>
    /// if true all other properties have no meaning.
    /// </summary>
    public bool IsSeparator { get; set; }

    /// <summary>
    /// if true just text property have a meaning.
    /// </summary>
    public bool IsGroupHeader { get; set; }

    /// <summary>
    /// used for MenuItem and translation identification.
    /// </summary>
    public string? Name { get; set; }

    /// <summary>
    /// text of the menu item.
    /// </summary>
    public string? Text { get; set; }

    /// <summary>
    /// tooltip text of the menu item.
    /// </summary>
    public string? ToolTipText { get; set; }

    /// <summary>
    /// image of the menu item.
    /// </summary>
    public IImage? Image { get; set; }

    public Keys ShortcutKeys { get; set; }

    public string? ShortcutKeyDisplayString { get; set; }

    /// <summary>
    /// execute on menu click.
    /// </summary>
    public Action? ExecuteAction;

    /// <summary>
    /// called if the menu item want to know if the Checked property
    /// should be true or false. If null then false.
    /// </summary>
    public Func<bool>? IsCheckedFunc;

    /// <summary>
    /// called if the menu item want to know if the Enabled property
    /// should be true or false. If null then true.
    /// </summary>
    public Func<bool>? IsEnabledFunc;

    /// <summary>
    /// To make the MenuCommand interact with all its associated menu items
    /// this method is used to register the all menu items that where generated by this MenuCommand.
    /// </summary>
    public void RegisterMenuItem(MenuItem menuItem)
    {
        _registeredMenuItems.Add(menuItem);
    }

    public void UnregisterMenuItems(IEnumerable<MenuItem> items)
    {
        foreach (MenuItem item in items)
        {
            _registeredMenuItems.Remove(item);
        }
    }

    public void SetCheckForRegisteredMenuItems()
    {
        if (IsCheckedFunc is not null)
        {
            bool isChecked = IsCheckedFunc();

            foreach (MenuItem item in _registeredMenuItems)
            {
                item.IsChecked = isChecked;
            }
        }

        if (IsEnabledFunc is not null)
        {
            bool isEnabled = IsEnabledFunc();

            foreach (MenuItem item in _registeredMenuItems)
            {
                item.IsEnabled = isEnabled;
            }
        }
    }

    public void UpdateMenuItemsShortcutKeyDisplayString()
    {
        foreach (MenuItem item in _registeredMenuItems)
        {
            item.InputGesture = ParseShortcut(ShortcutKeyDisplayString);
        }
    }

    private static Image? CreateIcon(IImage? image)
        => image is null
            ? null
            : new Image
            {
                Width = 16,
                Height = 16,
                Stretch = Stretch.Uniform,
                Source = image,
            };

    private static KeyGesture? ParseShortcut(string? shortcut)
    {
        if (string.IsNullOrWhiteSpace(shortcut))
        {
            return null;
        }

        try
        {
            return KeyGesture.Parse(shortcut.Split(',')[0].Trim());
        }
        catch (ArgumentException)
        {
            return null;
        }
    }
}
