namespace GitExtensions.ParityInventory;

// parity-scaffolding: Separates compiler-generated WinForms/Avalonia shell differences from product gaps.
internal static class FrameworkDeviationClassifier
{
    private const string DesignerMethodSummary =
        "<summary>Required method for Designer support - do not modify the contents of this method with the code editor.</summary>";
    private const string DesignerVariableSummary = "<summary>Required designer variable.</summary>";

    public static FrameworkComparisonInputs Classify(SourceInventory original, SourceInventory twin)
    {
        if (!twin.Parts.Any(part => part.Path.EndsWith(".axaml", StringComparison.Ordinal)))
        {
            return new FrameworkComparisonInputs(original, twin, []);
        }

        HashSet<MemberEntry> omittedOriginalMembers = [];
        HashSet<MemberEntry> omittedTwinMembers = [];
        HashSet<CommentEntry> omittedOriginalComments = [];
        List<AcceptedFrameworkDeviation> deviations = [];

        foreach (MemberEntry member in original.Members.Where(IsGeneratedDesignerMember))
        {
            omittedOriginalMembers.Add(member);
            deviations.Add(NewDeviation(
                "members",
                "member.generated-axaml",
                $"member/{member.Part}/{member.Kind}:{member.Name}",
                member.Part,
                GetExpectedTwinPart(original, member.Part),
                member.Name == "components"
                    ? "Avalonia views do not own a WinForms IContainer; their named controls and resources are owned by compiled AXAML."
                    : "Avalonia's AXAML compiler generates InitializeComponent and the named-control fields at build time.",
                member.Signature,
                member.Name == "components" ? null : "generated by compiled AXAML"));
        }

        MemberEntry? originalDispose = original.Members.FirstOrDefault(member =>
            member.Kind == "method"
            && member.Name == "Dispose"
            && member.Signature.Contains("bool disposing", StringComparison.Ordinal));
        MemberEntry? twinOnClosed = twin.Members.FirstOrDefault(member =>
            member.Kind == "method"
            && member.Name == "OnClosed"
            && member.Signature.Contains("EventArgs e", StringComparison.Ordinal));
        if (originalDispose is not null && twinOnClosed is not null)
        {
            omittedOriginalMembers.Add(originalDispose);
            omittedTwinMembers.Add(twinOnClosed);
            deviations.Add(NewDeviation(
                "members",
                "member.lifecycle-adapted",
                $"member/{originalDispose.Part}/method:Dispose",
                originalDispose.Part,
                twinOnClosed.Part,
                "Avalonia releases form-owned operations from Window.OnClosed because Window has no WinForms Dispose(bool) lifecycle.",
                originalDispose.Signature,
                twinOnClosed.Signature));
        }

        HashSet<string> originalFields = original.Members
            .Where(member => member.Kind == "field")
            .Select(member => member.Name)
            .ToHashSet(StringComparer.Ordinal);
        foreach (CommentEntry comment in original.Comments.Where(comment =>
                     IsGeneratedDesignerComment(comment, originalFields)))
        {
            omittedOriginalComments.Add(comment);
            deviations.Add(NewDeviation(
                "comments",
                "comment.generated-designer",
                $"comment/{comment.Part}/{comment.Anchor}/{comment.Placement}/{comment.Order}",
                comment.Part,
                GetExpectedTwinPart(original, comment.Part),
                "This is WinForms Designer boilerplate: the equivalent control identity or generated initializer is represented directly by compiled AXAML.",
                comment.Text,
                null));
        }

        return new FrameworkComparisonInputs(
            original with
            {
                Members = original.Members.Where(member => !omittedOriginalMembers.Contains(member)).ToArray(),
                Comments = original.Comments.Where(comment => !omittedOriginalComments.Contains(comment)).ToArray()
            },
            twin with
            {
                Members = twin.Members.Where(member => !omittedTwinMembers.Contains(member)).ToArray()
            },
            deviations
                .OrderBy(deviation => deviation.Category, StringComparer.Ordinal)
                .ThenBy(deviation => deviation.Code, StringComparer.Ordinal)
                .ThenBy(deviation => deviation.Path, StringComparer.Ordinal)
                .ToArray());
    }

    private static bool IsGeneratedDesignerMember(MemberEntry member) =>
        member.Part.EndsWith(".Designer.cs", StringComparison.Ordinal)
        && ((member.Kind == "field" && member.Name == "components")
            || (member.Kind == "method" && member.Name == "InitializeComponent"));

    private static bool IsGeneratedDesignerComment(
        CommentEntry comment,
        IReadOnlySet<string> originalFields)
    {
        if (!comment.Part.EndsWith(".Designer.cs", StringComparison.Ordinal))
        {
            return false;
        }

        if (comment.Anchor == "field:components")
        {
            return comment.Kind == "xmlDoc" && NormalizeXmlDoc(comment.Text) == DesignerVariableSummary;
        }

        if (comment.Anchor != "method:InitializeComponent()")
        {
            return false;
        }

        if (comment.Placement == "leading")
        {
            return comment.Kind == "xmlDoc" && NormalizeXmlDoc(comment.Text) == DesignerMethodSummary;
        }

        if (comment.Placement != "body" || comment.Kind != "singleLine")
        {
            return false;
        }

        if (comment.Text.Length == 0 || originalFields.Contains(comment.Text))
        {
            return true;
        }

        string designerSuffix = ".Designer.cs";
        string className = Path.GetFileName(comment.Part)[..^designerSuffix.Length];
        if (comment.Text == className)
        {
            return true;
        }

        int panelSeparator = comment.Text.LastIndexOf(".Panel", StringComparison.Ordinal);
        return panelSeparator > 0
            && originalFields.Contains(comment.Text[..panelSeparator])
            && comment.Text[(panelSeparator + ".Panel".Length)..] is "1" or "2";
    }

    private static string GetExpectedTwinPart(SourceInventory original, string originalPart) =>
        original.Parts.FirstOrDefault(part => part.Path == originalPart)?.ExpectedTwinPath
        ?? originalPart;

    private static string NormalizeXmlDoc(string text) =>
        text.Replace("> ", ">", StringComparison.Ordinal)
            .Replace(" </", "</", StringComparison.Ordinal);

    private static AcceptedFrameworkDeviation NewDeviation(
        string category,
        string code,
        string path,
        string originalPart,
        string twinPart,
        string rationale,
        string? originalValue,
        string? twinValue) =>
        new()
        {
            Category = category,
            Code = code,
            Path = path,
            OriginalPart = originalPart,
            TwinPart = twinPart,
            Rationale = rationale,
            OriginalValue = originalValue,
            TwinValue = twinValue
        };
}

internal sealed record FrameworkComparisonInputs(
    SourceInventory Original,
    SourceInventory Twin,
    IReadOnlyList<AcceptedFrameworkDeviation> Deviations);
