// <auto-generated />
// Generated by eng/tools/ImagesResxToAvalonia from GitUI/Properties/Images.resx.

using System.Collections.Concurrent;
using Avalonia.Controls;
using Avalonia.Media.Imaging;
using Avalonia.Platform;

namespace GitUI.Properties;

/// <summary>
/// Provides the original GitUI image-resource property names as cached Avalonia bitmaps.
/// </summary>
public static class Images
{
    private static readonly ConcurrentDictionary<string, Lazy<Bitmap>> _cache = new(StringComparer.Ordinal);
    private static readonly Lazy<WindowIcon> _applicationIcon = new(CreateApplicationIcon, LazyThreadSafetyMode.ExecutionAndPublication);
    private static readonly IReadOnlyDictionary<string, string> _resourcePaths =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            [nameof(StatusBadgeWaiting)] = "Resources/Icons/StatusBadgeWaiting.png",
            [nameof(StatusBadgeError)] = "Resources/Icons/StatusBadgeError.png",
            [nameof(StatusBadgeSuccess)] = "Resources/Icons/StatusBadgeSuccess.png",
            [nameof(HelpPullRebase)] = "Resources/Help/HelpPullRebase.png",
            [nameof(HelpCommandRebase)] = "Resources/Help/HelpCommandRebase.png",
            [nameof(HelpPullFetch)] = "Resources/Help/HelpPullFetch.png",
            [nameof(HelpCommandMerge)] = "Resources/Help/HelpCommandMerge.png",
            [nameof(HelpPullMerge)] = "Resources/Help/HelpPullMerge.png",
            [nameof(HelpCommandMergeFastForward)] = "Resources/Help/HelpCommandMergeFastForward.png",
            [nameof(HelpPullMergeFastForward)] = "Resources/Help/HelpPullMergeFastForward.png",
            [nameof(RepoStateClean)] = "Resources/Icons/RepoStateClean.png",
            [nameof(RepoStateMixed)] = "Resources/Icons/RepoStateMixed.png",
            [nameof(RepoStateDirty)] = "Resources/Icons/RepoStateDirty.png",
            [nameof(RepoStateStaged)] = "Resources/Icons/RepoStateStaged.png",
            [nameof(RepoStateDirtySubmodules)] = "Resources/Icons/RepoStateDirtySubmodules.png",
            [nameof(RepoStateUnknown)] = "Resources/Icons/RepoStateUnknown.png",
            [nameof(RepoStateUntrackedOnly)] = "Resources/Icons/RepoStateUntrackedOnly.png",
            [nameof(CommitSignatureError)] = "Resources/Icons/CommitSignatureError.png",
            [nameof(CommitSignatureOk)] = "Resources/Icons/CommitSignatureOk.png",
            [nameof(CommitSignatureWarning)] = "Resources/Icons/CommitSignatureWarning.png",
            [nameof(TagWarning)] = "Resources/Icons/TagWarning.png",
            [nameof(TagError)] = "Resources/Icons/TagError.png",
            [nameof(TagMany)] = "Resources/Icons/TagMany.png",
            [nameof(TagOk)] = "Resources/Icons/TagOk.png",
            [nameof(TagCreate)] = "Resources/Icons/TagCreate.png",
            [nameof(TagDelete)] = "Resources/Icons/TagDelete.png",
            [nameof(TagHorizontal)] = "Resources/Icons/TagHorizontal.png",
            [nameof(PuttyGen)] = "Resources/Icons/puttygen.png",
            [nameof(FolderSubmodule)] = "Resources/Icons/FolderSubmodule.png",
            [nameof(CommitTemplates)] = "Resources/Icons/CommitTemplates.png",
            [nameof(SaveAs)] = "Resources/Icons/SaveAs.png",
            [nameof(DonateBadge)] = "Resources/Icons/Donate.png",
            [nameof(Stash)] = "Resources/Icons/stash.png",
            [nameof(Putty)] = "Resources/Icons/putty.png",
            [nameof(ArrowUp)] = "Resources/Icons/ArrowUp.png",
            [nameof(Unmerged)] = "Resources/Icons/Unmerged.png",
            [nameof(Pageant)] = "Resources/Icons/pageant.png",
            [nameof(Pageant16)] = "Resources/Icons/Pageant16.png",
            [nameof(SolveMerge)] = "Resources/Icons/SolveMerge.png",
            [nameof(WorkingDirChanges)] = "Resources/Icons/WorkingDirChanges.png",
            [nameof(ArrowDown)] = "Resources/Icons/ArrowDown.png",
            [nameof(User80)] = "Resources/Icons/User80.png",
            [nameof(Renamed)] = "Resources/Icons/Renamed.png",
            [nameof(Push)] = "Resources/Icons/Push.png",
            [nameof(Pull)] = "Resources/Icons/Pull.png",
            [nameof(PullFetch)] = "Resources/Icons/PullFetch.png",
            [nameof(PullFetchPrune)] = "Resources/Icons/PullFetchPrune.png",
            [nameof(PullMerge)] = "Resources/Icons/PullMerge.png",
            [nameof(PullRebase)] = "Resources/Icons/PullRebase.png",
            [nameof(PullFetchAll)] = "Resources/Icons/PullFetchAll.png",
            [nameof(Globe)] = "Resources/Icons/Globe.png",
            [nameof(Branch)] = "Resources/Icons/Branch.png",
            [nameof(BranchLocal)] = "Resources/Icons/BranchLocal.png",
            [nameof(BranchLocalMerged)] = "Resources/Icons/BranchLocalMerged.png",
            [nameof(BranchRemote)] = "Resources/Icons/BranchRemote.png",
            [nameof(BranchRemoteMerged)] = "Resources/Icons/BranchRemoteMerged.png",
            [nameof(BranchLocalRoot)] = "Resources/Icons/LocalBranchRoot.png",
            [nameof(BranchRemoteRoot)] = "Resources/Icons/RemoteBranchRoot.png",
            [nameof(BranchCheckout)] = "Resources/Icons/BranchCheckout.png",
            [nameof(BranchCreate)] = "Resources/Icons/BranchCreate.png",
            [nameof(BranchFilter)] = "Resources/Icons/BranchFilter.png",
            [nameof(BranchFolder)] = "Resources/Icons/BranchFolder.png",
            [nameof(BranchDelete)] = "Resources/Icons/BranchDelete.png",
            [nameof(CollapseAll)] = "Resources/Icons/CollapseAll.png",
            [nameof(ExpandAll)] = "Resources/Icons/ExpandAll.png",
            [nameof(ResetWorkingDirChanges)] = "Resources/Icons/ResetWorkingDirChanges.png",
            [nameof(ResetCurrentBranchToHere)] = "Resources/Icons/ResetCurrentBranchToHere.png",
            [nameof(ResetFileTo)] = "Resources/Icons/ResetFileTo.png",
            [nameof(Merge)] = "Resources/Icons/Merge.png",
            [nameof(Rebase)] = "Resources/Icons/Rebase.png",
            [nameof(CherryPick)] = "Resources/Icons/CherryPick.png",
            [nameof(NavigateUp)] = "Resources/Icons/NavigateUp.png",
            [nameof(EditFile)] = "Resources/Icons/EditFile.png",
            [nameof(DeleteFile)] = "Resources/Icons/DeleteFile.png",
            [nameof(CloneRepoGit)] = "Resources/Icons/CloneRepoGit.png",
            [nameof(CloneRepoGitHub)] = "Resources/Icons/CloneRepoGitHub.png",
            [nameof(Save)] = "Resources/Icons/Save.png",
            [nameof(AddToGitIgnore)] = "Resources/Icons/AddToGitIgnore.png",
            [nameof(EditGitIgnore)] = "Resources/Icons/EditGitIgnore.png",
            [nameof(GotoCommit)] = "Resources/Icons/GotoCommit.png",
            [nameof(SelectBranch)] = "Resources/Icons/SelectBranch.png",
            [nameof(SelectRevision)] = "Resources/Icons/SelectRevision.png",
            [nameof(Stage)] = "Resources/Icons/Stage.png",
            [nameof(StageAll)] = "Resources/Icons/StageAll.png",
            [nameof(Unstage)] = "Resources/Icons/Unstage.png",
            [nameof(UnstageAll)] = "Resources/Icons/UnstageAll.png",
            [nameof(RepoCreate)] = "Resources/Icons/RepoCreate.png",
            [nameof(RepoOpen)] = "Resources/Icons/RepoOpen.png",
            [nameof(SubmodulesManage)] = "Resources/Icons/SubmodulesManage.png",
            [nameof(SubmodulesSync)] = "Resources/Icons/SubmodulesSync.png",
            [nameof(SubmodulesUpdate)] = "Resources/Icons/SubmodulesUpdate.png",
            [nameof(SubmoduleDirty)] = "Resources/Icons/SubmoduleDirty.png",
            [nameof(SubmoduleRevisionDown)] = "Resources/Icons/SubmoduleRevisionDown.png",
            [nameof(SubmoduleRevisionDownDirty)] = "Resources/Icons/SubmoduleRevisionDownDirty.png",
            [nameof(SubmoduleRevisionUp)] = "Resources/Icons/SubmoduleRevisionUp.png",
            [nameof(SubmoduleRevisionUpDirty)] = "Resources/Icons/SubmoduleRevisionUpDirty.png",
            [nameof(SubmoduleRevisionSemiDown)] = "Resources/Icons/SubmoduleRevisionSemiDown.png",
            [nameof(SubmoduleRevisionSemiDownDirty)] = "Resources/Icons/SubmoduleRevisionSemiDownDirty.png",
            [nameof(SubmoduleRevisionSemiUp)] = "Resources/Icons/SubmoduleRevisionSemiUp.png",
            [nameof(SubmoduleRevisionSemiUpDirty)] = "Resources/Icons/SubmoduleRevisionSemiUpDirty.png",
            [nameof(GotoCurrentRevision)] = "Resources/Icons/GotoCurrentRevision.png",
            [nameof(ShowOnlyFirstParent)] = "Resources/Icons/ShowOnlyFirstParent.png",
            [nameof(RemoteAdd)] = "Resources/Icons/RemoteAdd.png",
            [nameof(RemoteDelete)] = "Resources/Icons/RemoteDelete.png",
            [nameof(Blank)] = "Resources/Icons/Blank.png",
            [nameof(Key)] = "Resources/Icons/Key.png",
            [nameof(WhitespaceIgnoreAll)] = "Resources/Icons/WhitespaceIgnoreAll.png",
            [nameof(WhitespaceIgnore)] = "Resources/Icons/WhitespaceIgnore.png",
            [nameof(WhitespaceIgnoreEol)] = "Resources/Icons/WhitespaceIgnoreEol.png",
            [nameof(EyeClosed)] = "Resources/Icons/EyeClosed.png",
            [nameof(EyeOpened)] = "Resources/Icons/EyeOpened.png",
            [nameof(BulletAdd)] = "Resources/Icons/BulletAdd.png",
            [nameof(DashboardBackgroundGrey)] = "Resources/Backgrounds/DashboardBackgroundGrey.png",
            [nameof(DashboardBackgroundBlue)] = "Resources/Backgrounds/DashboardBackgroundBlue.png",
            [nameof(DashboardFolderError)] = "Resources/Icons/DashboardFolderError.png",
            [nameof(DashboardFolderGit)] = "Resources/Icons/DashboardFolderGit.png",
            [nameof(LayoutSidebarLeft)] = "Resources/Icons/LayoutSidebarLeft.png",
            [nameof(LayoutFooter)] = "Resources/Icons/LayoutFooter.png",
            [nameof(Bisect)] = "Resources/Icons/Bisect.png",
            [nameof(BisectGood)] = "Resources/Icons/BisectGood.png",
            [nameof(BisectBad)] = "Resources/Icons/BisectBad.png",
            [nameof(BisectSkip)] = "Resources/Icons/BisectSkip.png",
            [nameof(BisectStop)] = "Resources/Icons/BisectStop.png",
            [nameof(Bug)] = "Resources/Icons/bug.png",
            [nameof(Blame)] = "Resources/Icons/Blame.png",
            [nameof(Settings)] = "Resources/Icons/Settings.png",
            [nameof(CleanupRepo)] = "Resources/Icons/CleanupRepo.png",
            [nameof(Star)] = "Resources/Icons/star.png",
            [nameof(StarRemove)] = "Resources/Icons/StarRemove.png",
            [nameof(FileNew)] = "Resources/Icons/FileNew.png",
            [nameof(Book)] = "Resources/Icons/Book.png",
            [nameof(BrowseFileExplorer)] = "Resources/Icons/BrowseFileExplorer.png",
            [nameof(Console)] = "Resources/Icons/Console.png",
            [nameof(CopyToClipboard)] = "Resources/Icons/CopyToClipboard.png",
            [nameof(Develop)] = "Resources/Icons/Develop.png",
            [nameof(DollarSign)] = "Resources/Icons/DollarSign.png",
            [nameof(EditFilter)] = "Resources/Icons/EditFilter.png",
            [nameof(FileHistory)] = "Resources/Icons/FileHistory.png",
            [nameof(FixupAndSquashMessageMarker)] = "Resources/Icons/FixupAndSquashMessageMarker.png",
            [nameof(FileStatusAdded)] = "Resources/Icons/FileStatusAdded.png",
            [nameof(FileStatusAddedOnlyA)] = "Resources/Icons/FileStatusAddedOnlyA.png",
            [nameof(FileStatusAddedOnlyB)] = "Resources/Icons/FileStatusAddedOnlyB.png",
            [nameof(FileStatusAddedSame)] = "Resources/Icons/FileStatusAddedSame.png",
            [nameof(FileStatusAddedUnequal)] = "Resources/Icons/FileStatusAddedUnequal.png",
            [nameof(FileStatusModified)] = "Resources/Icons/FileStatusModified.png",
            [nameof(FileStatusModifiedOnlyA)] = "Resources/Icons/FileStatusModifiedOnlyA.png",
            [nameof(FileStatusModifiedOnlyB)] = "Resources/Icons/FileStatusModifiedOnlyB.png",
            [nameof(FileStatusModifiedSame)] = "Resources/Icons/FileStatusModifiedSame.png",
            [nameof(FileStatusModifiedUnequal)] = "Resources/Icons/FileStatusModifiedUnequal.png",
            [nameof(FileStatusRemoved)] = "Resources/Icons/FileStatusRemoved.png",
            [nameof(FileStatusRemovedOnlyA)] = "Resources/Icons/FileStatusRemovedOnlyA.png",
            [nameof(FileStatusRemovedOnlyB)] = "Resources/Icons/FileStatusRemovedOnlyB.png",
            [nameof(FileStatusRemovedSame)] = "Resources/Icons/FileStatusRemovedSame.png",
            [nameof(FileStatusRemovedUnequal)] = "Resources/Icons/FileStatusRemovedUnequal.png",
            [nameof(FileStatusCopied)] = "Resources/Icons/FileStatusCopied.png",
            [nameof(FileStatusCopiedOnlyA)] = "Resources/Icons/FileStatusCopiedOnlyA.png",
            [nameof(FileStatusCopiedOnlyB)] = "Resources/Icons/FileStatusCopiedOnlyB.png",
            [nameof(FileStatusCopiedSame)] = "Resources/Icons/FileStatusCopiedSame.png",
            [nameof(FileStatusCopiedUnequal)] = "Resources/Icons/FileStatusCopiedUnequal.png",
            [nameof(FileStatusRenamed)] = "Resources/Icons/FileStatusRenamed.png",
            [nameof(FileStatusRenamedOnlyA)] = "Resources/Icons/FileStatusRenamedOnlyA.png",
            [nameof(FileStatusRenamedOnlyB)] = "Resources/Icons/FileStatusRenamedOnlyB.png",
            [nameof(FileStatusRenamedSame)] = "Resources/Icons/FileStatusRenamedSame.png",
            [nameof(FileStatusRenamedUnequal)] = "Resources/Icons/FileStatusRenamedUnequal.png",
            [nameof(FileStatusUnknown)] = "Resources/Icons/FileStatusUnknown.png",
            [nameof(FileTree)] = "Resources/Icons/FileTree.png",
            [nameof(Preview)] = "Resources/Icons/Preview.png",
            [nameof(ReloadRevisions)] = "Resources/Icons/ReloadRevisions.png",
            [nameof(ViewFile)] = "Resources/Icons/ViewFile.png",
            [nameof(Warning)] = "Resources/Icons/Warning.png",
            [nameof(UiScrollBar)] = "Resources/Icons/ui-scroll-bar.png",
            [nameof(ShowWhitespace)] = "Resources/Icons/ShowWhitespace.png",
            [nameof(RecentRepositories)] = "Resources/Icons/RecentRepositories.png",
            [nameof(ShowEntireFile)] = "Resources/Icons/ShowEntireFile.png",
            [nameof(File)] = "Resources/Icons/File.png",
            [nameof(FolderClosed)] = "Resources/Icons/FolderClosed.png",
            [nameof(FolderOpen)] = "Resources/Icons/FolderOpen.png",
            [nameof(GitCommandLog)] = "Resources/Icons/GitCommandLog.png",
            [nameof(GotoManual)] = "Resources/Icons/GotoManual.png",
            [nameof(ReloadRevisionsDirty)] = "Resources/Icons/ReloadRevisionsDirty.png",
            [nameof(Remotes)] = "Resources/Icons/Remotes.png",
            [nameof(PatchApply)] = "Resources/Icons/PatchApply.png",
            [nameof(PatchView)] = "Resources/Icons/PatchView.png",
            [nameof(PatchFormat)] = "Resources/Icons/PatchFormat.png",
            [nameof(ShowThisBranchOnly)] = "Resources/Icons/ShowThisBranchOnly.png",
            [nameof(StopTrackingFile)] = "Resources/Icons/StopTrackingFile.png",
            [nameof(Translate)] = "Resources/Icons/Translate.png",
            [nameof(TreeCollapseAll)] = "Resources/Icons/TreeCollapseAll.png",
            [nameof(TreeExpandSubtree)] = "Resources/Icons/TreeExpandSubtree.png",
            [nameof(EditColor)] = "Resources/Icons/EditColor.png",
            [nameof(Difftastic)] = "Resources/Icons/difftastic.ico",
            [nameof(Checkout)] = "Resources/Icons/checkout.png",
            [nameof(CommitSummary)] = "Resources/Icons/CommitSummary.png",
            [nameof(Diff)] = "Resources/Icons/Diff.png",
            [nameof(DiffA)] = "Resources/Icons/DiffA.png",
            [nameof(DiffB)] = "Resources/Icons/DiffB.png",
            [nameof(DiffC)] = "Resources/Icons/DiffC.png",
            [nameof(DiffR)] = "Resources/Icons/DiffR.png",
            [nameof(GitHub)] = "Resources/Icons/github.png",
            [nameof(BitBucket)] = "Resources/Icons/BitBucket.png",
            [nameof(VisualStudioTeamServices)] = "Resources/Icons/VisualStudioTeamServices.png",
            [nameof(Information)] = "Resources/Icons/information.png",
            [nameof(Maintenance)] = "Resources/Icons/Maintenance.png",
            [nameof(CompressGitDatabase)] = "Resources/Icons/CompressGitDatabase.png",
            [nameof(RecoverLostObjects)] = "Resources/Icons/RecoverLostObjects.png",
            [nameof(DeleteIndexLock)] = "Resources/Icons/DeleteIndexLock.png",
            [nameof(EditGitConfig)] = "Resources/Icons/EditGitConfig.png",
            [nameof(Remote)] = "Resources/Icons/Remote.png",
            [nameof(RevertCommit)] = "Resources/Icons/RevertCommit.png",
            [nameof(WorkTree)] = "Resources/Icons/WorkTree.png",
            [nameof(Pin)] = "Resources/Icons/pin.png",
            [nameof(ArchiveRevision)] = "Resources/Icons/ArchiveRevision.png",
            [nameof(GoToFirstParentCommit)] = "Resources/Icons/GoToFirstParentCommit.png",
            [nameof(GoToLastParentCommit)] = "Resources/Icons/GoToLastParentCommit.png",
            [nameof(GoToParentCommit)] = "Resources/Icons/GoToParentCommit.png",
            [nameof(GoToMergeBaseCommit)] = "Resources/Icons/GoToMergeBaseCommit.png",
            [nameof(NavigateForward)] = "Resources/Icons/NavigateForward.png",
            [nameof(FunnelExclamation)] = "Resources/Icons/FunnelExclamation.png",
            [nameof(FunnelPencil)] = "Resources/Icons/FunnelPencil.png",
            [nameof(GoToChildCommit)] = "Resources/Icons/GoToChildCommit.png",
            [nameof(NavigateBackward)] = "Resources/Icons/NavigateBackward.png",
            [nameof(BugReport)] = "Resources/Icons/BugReport.png",
            [nameof(CheckForUpdates)] = "Resources/Icons/CheckForUpdates.png",
            [nameof(Changelog)] = "Resources/Icons/Changelog.png",
            [nameof(Author)] = "Resources/Icons/Author.png",
            [nameof(CommitId)] = "Resources/Icons/CommitId.png",
            [nameof(Date)] = "Resources/Icons/Date.png",
            [nameof(Message)] = "Resources/Icons/Message.png",
            [nameof(Tag)] = "Resources/Icons/Tag.png",
            [nameof(GitForWindows)] = "Resources/Icons/GitForWindows.png",
            [nameof(GitGui)] = "Resources/Icons/GitGui.png",
            [nameof(Gitk)] = "Resources/Icons/Gitk.png",
            [nameof(Advanced)] = "Resources/Icons/Advanced.png",
            [nameof(ClearLog)] = "Resources/Icons/ClearLog.png",
            [nameof(NumberOfLinesDecrease)] = "Resources/Icons/NumberOfLinesDecrease.png",
            [nameof(NumberOfLinesIncrease)] = "Resources/Icons/NumberOfLinesIncrease.png",
            [nameof(GitExtensionsLogoWide)] = "Resources/Logo/GitExtensionsLogoWide.png",
            [nameof(GitExtensionsLogo16)] = "Resources/Logo/git-extensions-logo-16px.png",
            [nameof(GitExtensionsLogo256)] = "Resources/Logo/git-extensions-logo-256px.png",
            [nameof(LayoutSidebarTopLeft)] = "Resources/Icons/LayoutSidebarTopLeft.png",
            [nameof(LayoutSidebarTopRight)] = "Resources/Icons/LayoutSidebarTopRight.png",
            [nameof(LayoutFooterTab)] = "Resources/Icons/LayoutFooterTab.png",
            [nameof(GitLogo16)] = "Resources/Icons/GitLogo16.png",
            [nameof(AdvancedSettings)] = "Resources/Icons/AdvancedSettings.png",
            [nameof(GeneralSettings)] = "Resources/Icons/GeneralSettings.png",
            [nameof(Appearance)] = "Resources/Icons/Appearance.png",
            [nameof(Plugin)] = "Resources/Icons/plugin.png",
            [nameof(ShellExtensions)] = "Resources/Icons/ShellExtensions.png",
            [nameof(Hotkey)] = "Resources/Icons/Hotkey.png",
            [nameof(Link)] = "Resources/Icons/Link.png",
            [nameof(Integration)] = "Resources/Icons/Integration.png",
            [nameof(Font)] = "Resources/Icons/Font.png",
            [nameof(Colors)] = "Resources/Icons/Colors.png",
            [nameof(PullFetchPruneAll)] = "Resources/Icons/PullFetchPruneAll.png",
            [nameof(RemoteEnableAndFetch)] = "Resources/Icons/RemoteEnableAndFetch.png",
            [nameof(DocumentTree)] = "Resources/Icons/DocumentTree.png",
            [nameof(SortBy)] = "Resources/Icons/SortBy.png",
            [nameof(PullRequest)] = "Resources/Icons/PullRequest.png",
            [nameof(cmd)] = "Resources/Icons/cmd.png",
            [nameof(powershell)] = "Resources/Icons/powershell.png",
            [nameof(pwsh)] = "Resources/Icons/pwsh.png",
            [nameof(StageAllFiltered)] = "Resources/Icons/StageAllFiltered.png",
            [nameof(UnstageAllFiltered)] = "Resources/Icons/UnstageAllFiltered.png",
            [nameof(VisualStudio16)] = "Resources/Icons/VisualStudio16.png",
            [nameof(ResetAnotherBranchToHere)] = "Resources/Icons/ResetAnotherBranchToHere.png",
        };

    internal static IReadOnlyDictionary<string, string> ResourcePaths => _resourcePaths;

    public static WindowIcon ApplicationIcon => _applicationIcon.Value;

    public static Bitmap StatusBadgeWaiting => Get(nameof(StatusBadgeWaiting));

    public static Bitmap StatusBadgeError => Get(nameof(StatusBadgeError));

    public static Bitmap StatusBadgeSuccess => Get(nameof(StatusBadgeSuccess));

    public static Bitmap HelpPullRebase => Get(nameof(HelpPullRebase));

    public static Bitmap HelpCommandRebase => Get(nameof(HelpCommandRebase));

    public static Bitmap HelpPullFetch => Get(nameof(HelpPullFetch));

    public static Bitmap HelpCommandMerge => Get(nameof(HelpCommandMerge));

    public static Bitmap HelpPullMerge => Get(nameof(HelpPullMerge));

    public static Bitmap HelpCommandMergeFastForward => Get(nameof(HelpCommandMergeFastForward));

    public static Bitmap HelpPullMergeFastForward => Get(nameof(HelpPullMergeFastForward));

    public static Bitmap RepoStateClean => Get(nameof(RepoStateClean));

    public static Bitmap RepoStateMixed => Get(nameof(RepoStateMixed));

    public static Bitmap RepoStateDirty => Get(nameof(RepoStateDirty));

    public static Bitmap RepoStateStaged => Get(nameof(RepoStateStaged));

    public static Bitmap RepoStateDirtySubmodules => Get(nameof(RepoStateDirtySubmodules));

    public static Bitmap RepoStateUnknown => Get(nameof(RepoStateUnknown));

    public static Bitmap RepoStateUntrackedOnly => Get(nameof(RepoStateUntrackedOnly));

    public static Bitmap CommitSignatureError => Get(nameof(CommitSignatureError));

    public static Bitmap CommitSignatureOk => Get(nameof(CommitSignatureOk));

    public static Bitmap CommitSignatureWarning => Get(nameof(CommitSignatureWarning));

    public static Bitmap TagWarning => Get(nameof(TagWarning));

    public static Bitmap TagError => Get(nameof(TagError));

    public static Bitmap TagMany => Get(nameof(TagMany));

    public static Bitmap TagOk => Get(nameof(TagOk));

    public static Bitmap TagCreate => Get(nameof(TagCreate));

    public static Bitmap TagDelete => Get(nameof(TagDelete));

    public static Bitmap TagHorizontal => Get(nameof(TagHorizontal));

    public static Bitmap PuttyGen => Get(nameof(PuttyGen));

    public static Bitmap FolderSubmodule => Get(nameof(FolderSubmodule));

    public static Bitmap CommitTemplates => Get(nameof(CommitTemplates));

    public static Bitmap SaveAs => Get(nameof(SaveAs));

    public static Bitmap DonateBadge => Get(nameof(DonateBadge));

    public static Bitmap Stash => Get(nameof(Stash));

    public static Bitmap Putty => Get(nameof(Putty));

    public static Bitmap ArrowUp => Get(nameof(ArrowUp));

    public static Bitmap Unmerged => Get(nameof(Unmerged));

    public static Bitmap Pageant => Get(nameof(Pageant));

    public static Bitmap Pageant16 => Get(nameof(Pageant16));

    public static Bitmap SolveMerge => Get(nameof(SolveMerge));

    public static Bitmap WorkingDirChanges => Get(nameof(WorkingDirChanges));

    public static Bitmap ArrowDown => Get(nameof(ArrowDown));

    public static Bitmap User80 => Get(nameof(User80));

    public static Bitmap Renamed => Get(nameof(Renamed));

    public static Bitmap Push => Get(nameof(Push));

    public static Bitmap Pull => Get(nameof(Pull));

    public static Bitmap PullFetch => Get(nameof(PullFetch));

    public static Bitmap PullFetchPrune => Get(nameof(PullFetchPrune));

    public static Bitmap PullMerge => Get(nameof(PullMerge));

    public static Bitmap PullRebase => Get(nameof(PullRebase));

    public static Bitmap PullFetchAll => Get(nameof(PullFetchAll));

    public static Bitmap Globe => Get(nameof(Globe));

    public static Bitmap Branch => Get(nameof(Branch));

    public static Bitmap BranchLocal => Get(nameof(BranchLocal));

    public static Bitmap BranchLocalMerged => Get(nameof(BranchLocalMerged));

    public static Bitmap BranchRemote => Get(nameof(BranchRemote));

    public static Bitmap BranchRemoteMerged => Get(nameof(BranchRemoteMerged));

    public static Bitmap BranchLocalRoot => Get(nameof(BranchLocalRoot));

    public static Bitmap BranchRemoteRoot => Get(nameof(BranchRemoteRoot));

    public static Bitmap BranchCheckout => Get(nameof(BranchCheckout));

    public static Bitmap BranchCreate => Get(nameof(BranchCreate));

    public static Bitmap BranchFilter => Get(nameof(BranchFilter));

    public static Bitmap BranchFolder => Get(nameof(BranchFolder));

    public static Bitmap BranchDelete => Get(nameof(BranchDelete));

    public static Bitmap CollapseAll => Get(nameof(CollapseAll));

    public static Bitmap ExpandAll => Get(nameof(ExpandAll));

    public static Bitmap ResetWorkingDirChanges => Get(nameof(ResetWorkingDirChanges));

    public static Bitmap ResetCurrentBranchToHere => Get(nameof(ResetCurrentBranchToHere));

    public static Bitmap ResetFileTo => Get(nameof(ResetFileTo));

    public static Bitmap Merge => Get(nameof(Merge));

    public static Bitmap Rebase => Get(nameof(Rebase));

    public static Bitmap CherryPick => Get(nameof(CherryPick));

    public static Bitmap NavigateUp => Get(nameof(NavigateUp));

    public static Bitmap EditFile => Get(nameof(EditFile));

    public static Bitmap DeleteFile => Get(nameof(DeleteFile));

    public static Bitmap CloneRepoGit => Get(nameof(CloneRepoGit));

    public static Bitmap CloneRepoGitHub => Get(nameof(CloneRepoGitHub));

    public static Bitmap Save => Get(nameof(Save));

    public static Bitmap AddToGitIgnore => Get(nameof(AddToGitIgnore));

    public static Bitmap EditGitIgnore => Get(nameof(EditGitIgnore));

    public static Bitmap GotoCommit => Get(nameof(GotoCommit));

    public static Bitmap SelectBranch => Get(nameof(SelectBranch));

    public static Bitmap SelectRevision => Get(nameof(SelectRevision));

    public static Bitmap Stage => Get(nameof(Stage));

    public static Bitmap StageAll => Get(nameof(StageAll));

    public static Bitmap Unstage => Get(nameof(Unstage));

    public static Bitmap UnstageAll => Get(nameof(UnstageAll));

    public static Bitmap RepoCreate => Get(nameof(RepoCreate));

    public static Bitmap RepoOpen => Get(nameof(RepoOpen));

    public static Bitmap SubmodulesManage => Get(nameof(SubmodulesManage));

    public static Bitmap SubmodulesSync => Get(nameof(SubmodulesSync));

    public static Bitmap SubmodulesUpdate => Get(nameof(SubmodulesUpdate));

    public static Bitmap SubmoduleDirty => Get(nameof(SubmoduleDirty));

    public static Bitmap SubmoduleRevisionDown => Get(nameof(SubmoduleRevisionDown));

    public static Bitmap SubmoduleRevisionDownDirty => Get(nameof(SubmoduleRevisionDownDirty));

    public static Bitmap SubmoduleRevisionUp => Get(nameof(SubmoduleRevisionUp));

    public static Bitmap SubmoduleRevisionUpDirty => Get(nameof(SubmoduleRevisionUpDirty));

    public static Bitmap SubmoduleRevisionSemiDown => Get(nameof(SubmoduleRevisionSemiDown));

    public static Bitmap SubmoduleRevisionSemiDownDirty => Get(nameof(SubmoduleRevisionSemiDownDirty));

    public static Bitmap SubmoduleRevisionSemiUp => Get(nameof(SubmoduleRevisionSemiUp));

    public static Bitmap SubmoduleRevisionSemiUpDirty => Get(nameof(SubmoduleRevisionSemiUpDirty));

    public static Bitmap GotoCurrentRevision => Get(nameof(GotoCurrentRevision));

    public static Bitmap ShowOnlyFirstParent => Get(nameof(ShowOnlyFirstParent));

    public static Bitmap RemoteAdd => Get(nameof(RemoteAdd));

    public static Bitmap RemoteDelete => Get(nameof(RemoteDelete));

    public static Bitmap Blank => Get(nameof(Blank));

    public static Bitmap Key => Get(nameof(Key));

    public static Bitmap WhitespaceIgnoreAll => Get(nameof(WhitespaceIgnoreAll));

    public static Bitmap WhitespaceIgnore => Get(nameof(WhitespaceIgnore));

    public static Bitmap WhitespaceIgnoreEol => Get(nameof(WhitespaceIgnoreEol));

    public static Bitmap EyeClosed => Get(nameof(EyeClosed));

    public static Bitmap EyeOpened => Get(nameof(EyeOpened));

    public static Bitmap BulletAdd => Get(nameof(BulletAdd));

    public static Bitmap DashboardBackgroundGrey => Get(nameof(DashboardBackgroundGrey));

    public static Bitmap DashboardBackgroundBlue => Get(nameof(DashboardBackgroundBlue));

    public static Bitmap DashboardFolderError => Get(nameof(DashboardFolderError));

    public static Bitmap DashboardFolderGit => Get(nameof(DashboardFolderGit));

    public static Bitmap LayoutSidebarLeft => Get(nameof(LayoutSidebarLeft));

    public static Bitmap LayoutFooter => Get(nameof(LayoutFooter));

    public static Bitmap Bisect => Get(nameof(Bisect));

    public static Bitmap BisectGood => Get(nameof(BisectGood));

    public static Bitmap BisectBad => Get(nameof(BisectBad));

    public static Bitmap BisectSkip => Get(nameof(BisectSkip));

    public static Bitmap BisectStop => Get(nameof(BisectStop));

    public static Bitmap Bug => Get(nameof(Bug));

    public static Bitmap Blame => Get(nameof(Blame));

    public static Bitmap Settings => Get(nameof(Settings));

    public static Bitmap CleanupRepo => Get(nameof(CleanupRepo));

    public static Bitmap Star => Get(nameof(Star));

    public static Bitmap StarRemove => Get(nameof(StarRemove));

    public static Bitmap FileNew => Get(nameof(FileNew));

    public static Bitmap Book => Get(nameof(Book));

    public static Bitmap BrowseFileExplorer => Get(nameof(BrowseFileExplorer));

    public static Bitmap Console => Get(nameof(Console));

    public static Bitmap CopyToClipboard => Get(nameof(CopyToClipboard));

    public static Bitmap Develop => Get(nameof(Develop));

    public static Bitmap DollarSign => Get(nameof(DollarSign));

    public static Bitmap EditFilter => Get(nameof(EditFilter));

    public static Bitmap FileHistory => Get(nameof(FileHistory));

    public static Bitmap FixupAndSquashMessageMarker => Get(nameof(FixupAndSquashMessageMarker));

    public static Bitmap FileStatusAdded => Get(nameof(FileStatusAdded));

    public static Bitmap FileStatusAddedOnlyA => Get(nameof(FileStatusAddedOnlyA));

    public static Bitmap FileStatusAddedOnlyB => Get(nameof(FileStatusAddedOnlyB));

    public static Bitmap FileStatusAddedSame => Get(nameof(FileStatusAddedSame));

    public static Bitmap FileStatusAddedUnequal => Get(nameof(FileStatusAddedUnequal));

    public static Bitmap FileStatusModified => Get(nameof(FileStatusModified));

    public static Bitmap FileStatusModifiedOnlyA => Get(nameof(FileStatusModifiedOnlyA));

    public static Bitmap FileStatusModifiedOnlyB => Get(nameof(FileStatusModifiedOnlyB));

    public static Bitmap FileStatusModifiedSame => Get(nameof(FileStatusModifiedSame));

    public static Bitmap FileStatusModifiedUnequal => Get(nameof(FileStatusModifiedUnequal));

    public static Bitmap FileStatusRemoved => Get(nameof(FileStatusRemoved));

    public static Bitmap FileStatusRemovedOnlyA => Get(nameof(FileStatusRemovedOnlyA));

    public static Bitmap FileStatusRemovedOnlyB => Get(nameof(FileStatusRemovedOnlyB));

    public static Bitmap FileStatusRemovedSame => Get(nameof(FileStatusRemovedSame));

    public static Bitmap FileStatusRemovedUnequal => Get(nameof(FileStatusRemovedUnequal));

    public static Bitmap FileStatusCopied => Get(nameof(FileStatusCopied));

    public static Bitmap FileStatusCopiedOnlyA => Get(nameof(FileStatusCopiedOnlyA));

    public static Bitmap FileStatusCopiedOnlyB => Get(nameof(FileStatusCopiedOnlyB));

    public static Bitmap FileStatusCopiedSame => Get(nameof(FileStatusCopiedSame));

    public static Bitmap FileStatusCopiedUnequal => Get(nameof(FileStatusCopiedUnequal));

    public static Bitmap FileStatusRenamed => Get(nameof(FileStatusRenamed));

    public static Bitmap FileStatusRenamedOnlyA => Get(nameof(FileStatusRenamedOnlyA));

    public static Bitmap FileStatusRenamedOnlyB => Get(nameof(FileStatusRenamedOnlyB));

    public static Bitmap FileStatusRenamedSame => Get(nameof(FileStatusRenamedSame));

    public static Bitmap FileStatusRenamedUnequal => Get(nameof(FileStatusRenamedUnequal));

    public static Bitmap FileStatusUnknown => Get(nameof(FileStatusUnknown));

    public static Bitmap FileTree => Get(nameof(FileTree));

    public static Bitmap Preview => Get(nameof(Preview));

    public static Bitmap ReloadRevisions => Get(nameof(ReloadRevisions));

    public static Bitmap ViewFile => Get(nameof(ViewFile));

    public static Bitmap Warning => Get(nameof(Warning));

    public static Bitmap UiScrollBar => Get(nameof(UiScrollBar));

    public static Bitmap ShowWhitespace => Get(nameof(ShowWhitespace));

    public static Bitmap RecentRepositories => Get(nameof(RecentRepositories));

    public static Bitmap ShowEntireFile => Get(nameof(ShowEntireFile));

    public static Bitmap File => Get(nameof(File));

    public static Bitmap FolderClosed => Get(nameof(FolderClosed));

    public static Bitmap FolderOpen => Get(nameof(FolderOpen));

    public static Bitmap GitCommandLog => Get(nameof(GitCommandLog));

    public static Bitmap GotoManual => Get(nameof(GotoManual));

    public static Bitmap ReloadRevisionsDirty => Get(nameof(ReloadRevisionsDirty));

    public static Bitmap Remotes => Get(nameof(Remotes));

    public static Bitmap PatchApply => Get(nameof(PatchApply));

    public static Bitmap PatchView => Get(nameof(PatchView));

    public static Bitmap PatchFormat => Get(nameof(PatchFormat));

    public static Bitmap ShowThisBranchOnly => Get(nameof(ShowThisBranchOnly));

    public static Bitmap StopTrackingFile => Get(nameof(StopTrackingFile));

    public static Bitmap Translate => Get(nameof(Translate));

    public static Bitmap TreeCollapseAll => Get(nameof(TreeCollapseAll));

    public static Bitmap TreeExpandSubtree => Get(nameof(TreeExpandSubtree));

    public static Bitmap EditColor => Get(nameof(EditColor));

    public static Bitmap Difftastic => Get(nameof(Difftastic));

    public static Bitmap Checkout => Get(nameof(Checkout));

    public static Bitmap CommitSummary => Get(nameof(CommitSummary));

    public static Bitmap Diff => Get(nameof(Diff));

    public static Bitmap DiffA => Get(nameof(DiffA));

    public static Bitmap DiffB => Get(nameof(DiffB));

    public static Bitmap DiffC => Get(nameof(DiffC));

    public static Bitmap DiffR => Get(nameof(DiffR));

    public static Bitmap GitHub => Get(nameof(GitHub));

    public static Bitmap BitBucket => Get(nameof(BitBucket));

    public static Bitmap VisualStudioTeamServices => Get(nameof(VisualStudioTeamServices));

    public static Bitmap Information => Get(nameof(Information));

    public static Bitmap Maintenance => Get(nameof(Maintenance));

    public static Bitmap CompressGitDatabase => Get(nameof(CompressGitDatabase));

    public static Bitmap RecoverLostObjects => Get(nameof(RecoverLostObjects));

    public static Bitmap DeleteIndexLock => Get(nameof(DeleteIndexLock));

    public static Bitmap EditGitConfig => Get(nameof(EditGitConfig));

    public static Bitmap Remote => Get(nameof(Remote));

    public static Bitmap RevertCommit => Get(nameof(RevertCommit));

    public static Bitmap WorkTree => Get(nameof(WorkTree));

    public static Bitmap Pin => Get(nameof(Pin));

    public static Bitmap ArchiveRevision => Get(nameof(ArchiveRevision));

    public static Bitmap GoToFirstParentCommit => Get(nameof(GoToFirstParentCommit));

    public static Bitmap GoToLastParentCommit => Get(nameof(GoToLastParentCommit));

    public static Bitmap GoToParentCommit => Get(nameof(GoToParentCommit));

    public static Bitmap GoToMergeBaseCommit => Get(nameof(GoToMergeBaseCommit));

    public static Bitmap NavigateForward => Get(nameof(NavigateForward));

    public static Bitmap FunnelExclamation => Get(nameof(FunnelExclamation));

    public static Bitmap FunnelPencil => Get(nameof(FunnelPencil));

    public static Bitmap GoToChildCommit => Get(nameof(GoToChildCommit));

    public static Bitmap NavigateBackward => Get(nameof(NavigateBackward));

    public static Bitmap BugReport => Get(nameof(BugReport));

    public static Bitmap CheckForUpdates => Get(nameof(CheckForUpdates));

    public static Bitmap Changelog => Get(nameof(Changelog));

    public static Bitmap Author => Get(nameof(Author));

    public static Bitmap CommitId => Get(nameof(CommitId));

    public static Bitmap Date => Get(nameof(Date));

    public static Bitmap Message => Get(nameof(Message));

    public static Bitmap Tag => Get(nameof(Tag));

    public static Bitmap GitForWindows => Get(nameof(GitForWindows));

    public static Bitmap GitGui => Get(nameof(GitGui));

    public static Bitmap Gitk => Get(nameof(Gitk));

    public static Bitmap Advanced => Get(nameof(Advanced));

    public static Bitmap ClearLog => Get(nameof(ClearLog));

    public static Bitmap NumberOfLinesDecrease => Get(nameof(NumberOfLinesDecrease));

    public static Bitmap NumberOfLinesIncrease => Get(nameof(NumberOfLinesIncrease));

    public static Bitmap GitExtensionsLogoWide => Get(nameof(GitExtensionsLogoWide));

    public static Bitmap GitExtensionsLogo16 => Get(nameof(GitExtensionsLogo16));

    public static Bitmap GitExtensionsLogo256 => Get(nameof(GitExtensionsLogo256));

    public static Bitmap LayoutSidebarTopLeft => Get(nameof(LayoutSidebarTopLeft));

    public static Bitmap LayoutSidebarTopRight => Get(nameof(LayoutSidebarTopRight));

    public static Bitmap LayoutFooterTab => Get(nameof(LayoutFooterTab));

    public static Bitmap GitLogo16 => Get(nameof(GitLogo16));

    public static Bitmap AdvancedSettings => Get(nameof(AdvancedSettings));

    public static Bitmap GeneralSettings => Get(nameof(GeneralSettings));

    public static Bitmap Appearance => Get(nameof(Appearance));

    public static Bitmap Plugin => Get(nameof(Plugin));

    public static Bitmap ShellExtensions => Get(nameof(ShellExtensions));

    public static Bitmap Hotkey => Get(nameof(Hotkey));

    public static Bitmap Link => Get(nameof(Link));

    public static Bitmap Integration => Get(nameof(Integration));

    public static Bitmap Font => Get(nameof(Font));

    public static Bitmap Colors => Get(nameof(Colors));

    public static Bitmap PullFetchPruneAll => Get(nameof(PullFetchPruneAll));

    public static Bitmap RemoteEnableAndFetch => Get(nameof(RemoteEnableAndFetch));

    public static Bitmap DocumentTree => Get(nameof(DocumentTree));

    public static Bitmap SortBy => Get(nameof(SortBy));

    public static Bitmap PullRequest => Get(nameof(PullRequest));

    public static Bitmap cmd => Get(nameof(cmd));

    public static Bitmap powershell => Get(nameof(powershell));

    public static Bitmap pwsh => Get(nameof(pwsh));

    public static Bitmap StageAllFiltered => Get(nameof(StageAllFiltered));

    public static Bitmap UnstageAllFiltered => Get(nameof(UnstageAllFiltered));

    public static Bitmap VisualStudio16 => Get(nameof(VisualStudio16));

    public static Bitmap ResetAnotherBranchToHere => Get(nameof(ResetAnotherBranchToHere));

    private static Bitmap Get(string name)
    {
        string resourcePath = _resourcePaths[name];
        return _cache.GetOrAdd(
            resourcePath,
            static path => new Lazy<Bitmap>(
                () =>
                {
                    using Stream stream = AssetLoader.Open(new Uri("avares://GitUI.Avalonia/" + path));
                    return new Bitmap(stream);
                },
                LazyThreadSafetyMode.ExecutionAndPublication)).Value;
    }

    private static WindowIcon CreateApplicationIcon()
    {
        using Stream stream = AssetLoader.Open(new Uri("avares://GitUI.Avalonia/" + _resourcePaths[nameof(GitExtensionsLogo256)]));
        return new WindowIcon(stream);
    }
}
