// <auto-generated />
// Exposes the original GitUI string-resource property names by reading the packaged
// Resources.resx (inline string entries) and ChangeLog.md. The WinForms resource designer
// mixes System.Drawing image accessors with these strings, so it cannot be linked directly;
// the images already have their own generated Images.g.cs twin.

#nullable enable

using System.Xml.Linq;
using Avalonia.Platform;

namespace GitUI.Properties;

/// <summary>
/// Provides the original GitUI string-resource property names (contributor lists and changelog).
/// </summary>
public static class Resources
{
    private static readonly Lazy<IReadOnlyDictionary<string, string>> _strings =
        new(LoadStrings, LazyThreadSafetyMode.ExecutionAndPublication);
    private static readonly Lazy<string> _changeLog =
        new(LoadChangeLog, LazyThreadSafetyMode.ExecutionAndPublication);

    public static string Team => Get(nameof(Team));
    public static string Coders => Get(nameof(Coders));
    public static string Translators => Get(nameof(Translators));
    public static string Designers => Get(nameof(Designers));
    public static string ChangeLog => _changeLog.Value;

    private static string Get(string name)
        => _strings.Value.TryGetValue(name, out string? value) ? value : string.Empty;

    private static IReadOnlyDictionary<string, string> LoadStrings()
    {
        using Stream stream = AssetLoader.Open(new Uri("avares://GitUI.Avalonia/Properties/Resources.resx"));
        XDocument document = XDocument.Load(stream);
        Dictionary<string, string> result = new(StringComparer.Ordinal);
        foreach (XElement data in document.Root?.Elements("data") ?? [])
        {
            // Only inline string entries carry the value directly; typed entries (image/file refs) are skipped.
            if (data.Attribute("type") is not null || data.Attribute("name") is not { } name)
            {
                continue;
            }

            result[name.Value] = data.Element("value")?.Value ?? string.Empty;
        }

        return result;
    }

    private static string LoadChangeLog()
    {
        using Stream stream = AssetLoader.Open(new Uri("avares://GitUI.Avalonia/Resources/ChangeLog.md"));
        using StreamReader reader = new(stream);
        return reader.ReadToEnd();
    }
}
