//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bitbucket.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bitbucket.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the base URL to Bitbucket.
        /// </summary>
        internal static string BitbucketBaseUrl {
            get {
                return ResourceManager.GetString("BitbucketBaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable SSL verification.
        /// </summary>
        internal static string BitbucketDisableSsl {
            get {
                return ResourceManager.GetString("BitbucketDisableSsl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitbucket Password.
        /// </summary>
        internal static string BitbucketPassword {
            get {
                return ResourceManager.GetString("BitbucketPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitbucket Username.
        /// </summary>
        internal static string BitbucketUsername {
            get {
                return ResourceManager.GetString("BitbucketUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        internal static string BtnApprove {
            get {
                return ResourceManager.GetString("BtnApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string BtnCreate {
            get {
                return ResourceManager.GetString("BtnCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge.
        /// </summary>
        internal static string BtnMerge {
            get {
                return ResourceManager.GetString("BtnMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} committed
        ///{1}.
        /// </summary>
        internal static string Committed {
            get {
                return ResourceManager.GetString("Committed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitbucket Server.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitbucket Server.
        /// </summary>
        internal static string FormText {
            get {
                return ResourceManager.GetString("FormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull Request Info.
        /// </summary>
        internal static string GroupBoxCreatePullRequest {
            get {
                return ResourceManager.GetString("GroupBoxCreatePullRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string GroupBoxInformation {
            get {
                return ResourceManager.GetString("GroupBoxInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull Request Info.
        /// </summary>
        internal static string GroupBoxPullRequestInfo {
            get {
                return ResourceManager.GetString("GroupBoxPullRequestInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string GroupBoxSource {
            get {
                return ResourceManager.GetString("GroupBoxSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string GroupBoxSourceRepoView {
            get {
                return ResourceManager.GetString("GroupBoxSourceRepoView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        internal static string GroupBoxTarget {
            get {
                return ResourceManager.GetString("GroupBoxTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        internal static string GroupBoxTargetRepoView {
            get {
                return ResourceManager.GetString("GroupBoxTargetRepoView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string LblAuthor {
            get {
                return ResourceManager.GetString("LblAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        internal static string LblBranchView {
            get {
                return ResourceManager.GetString("LblBranchView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string LblDescription {
            get {
                return ResourceManager.GetString("LblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string LblDescriptionView {
            get {
                return ResourceManager.GetString("LblDescriptionView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository.
        /// </summary>
        internal static string LblRepositoryView {
            get {
                return ResourceManager.GetString("LblRepositoryView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviewer (approved).
        /// </summary>
        internal static string LblReviewerView {
            get {
                return ResourceManager.GetString("LblReviewerView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        internal static string LblSourceBranch {
            get {
                return ResourceManager.GetString("LblSourceBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository.
        /// </summary>
        internal static string LblSourceRepository {
            get {
                return ResourceManager.GetString("LblSourceRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository.
        /// </summary>
        internal static string LblSourceRepoView {
            get {
                return ResourceManager.GetString("LblSourceRepoView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string LblState {
            get {
                return ResourceManager.GetString("LblState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        internal static string LblTargetBranch {
            get {
                return ResourceManager.GetString("LblTargetBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository.
        /// </summary>
        internal static string LblTargetRepository {
            get {
                return ResourceManager.GetString("LblTargetRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        internal static string LblTargetRepoView {
            get {
                return ResourceManager.GetString("LblTargetRepoView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string LblTitle {
            get {
                return ResourceManager.GetString("LblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string LblTitleView {
            get {
                return ResourceManager.GetString("LblTitleView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right-click to copy link.
        /// </summary>
        internal static string LinkLabelToolTip {
            get {
                return ResourceManager.GetString("LinkLabelToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Pull Request.
        /// </summary>
        internal static string TabCreate {
            get {
                return ResourceManager.GetString("TabCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Pull Requests.
        /// </summary>
        internal static string TabView {
            get {
                return ResourceManager.GetString("TabView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your repository is not hosted in BitBucket Server..
        /// </summary>
        internal static string YourRepositoryIsNotInBitbucket {
            get {
                return ResourceManager.GetString("YourRepositoryIsNotInBitbucket", resourceCulture);
            }
        }
    }
}
