//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gource.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gource.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments.
        /// </summary>
        internal static string ArgumentsLabel {
            get {
                return ResourceManager.GetString("ArgumentsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Button1 {
            get {
                return ResourceManager.GetString("Button1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} bytes downloaded..
        /// </summary>
        internal static string BytesDownloaded {
            get {
                return ResourceManager.GetString("BytesDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find Gource.
        ///Please download Gource and set the path in the plugins settings dialog..
        /// </summary>
        internal static string CannotFindGource {
            get {
                return ResourceManager.GetString("CannotFindGource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current directory is not a valid git repository.
        ///
        ///Gource can be only be started from a valid git repository..
        /// </summary>
        internal static string CurrentDirectoryIsNotValidGit {
            get {
                return ResourceManager.GetString("CurrentDirectoryIsNotValidGit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gource.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading failed.
        ///Please download Gource and set the path in the plugins settings dialog..
        /// </summary>
        internal static string DownloadingFailed {
            get {
                return ResourceManager.GetString("DownloadingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no path to Gource configured.
        ///
        ///Do you want to automatically download Gource?.
        /// </summary>
        internal static string DoYouWantDownloadGource {
            get {
                return ResourceManager.GetString("DoYouWantDownloadGource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gource.
        /// </summary>
        internal static string FormText {
            get {
                return ResourceManager.GetString("FormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gource.
        /// </summary>
        internal static string Gource {
            get {
                return ResourceManager.GetString("Gource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments.
        /// </summary>
        internal static string GourceArguments {
            get {
                return ResourceManager.GetString("GourceArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string GourceBrowse {
            get {
                return ResourceManager.GetString("GourceBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gource has been downloaded and unzipped..
        /// </summary>
        internal static string GourceDownloadedAndUnzipped {
            get {
                return ResourceManager.GetString("GourceDownloadedAndUnzipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to Gource.
        /// </summary>
        internal static string GourcePath {
            get {
                return ResourceManager.GetString("GourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to Gource.
        /// </summary>
        internal static string Label1 {
            get {
                return ResourceManager.GetString("Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository.
        /// </summary>
        internal static string Label2 {
            get {
                return ResourceManager.GetString("Label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gource project.
        /// </summary>
        internal static string LinkLabel1 {
            get {
                return ResourceManager.GetString("LinkLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gource command line.
        /// </summary>
        internal static string LinkLabel2 {
            get {
                return ResourceManager.GetString("LinkLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find Gource in the configured path: {0}.
        ///
        ///Do you want to reset the configured path?.
        /// </summary>
        internal static string ResetConfigPath {
            get {
                return ResourceManager.GetString("ResetConfigPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string WorkingDirBrowse {
            get {
                return ResourceManager.GetString("WorkingDirBrowse", resourceCulture);
            }
        }
    }
}
