//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeleteUnusedBranches.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeleteUnusedBranches.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete {0} selected branches?.
        /// </summary>
        internal static string AreYouSureToDelete {
            get {
                return ResourceManager.GetString("AreYouSureToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last author.
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/{1} branches selected..
        /// </summary>
        internal static string BranchesSelected {
            get {
                return ResourceManager.GetString("BranchesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string ButtonSettingsText {
            get {
                return ResourceManager.GetString("ButtonSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose branches to delete. Only branches that are fully merged in &apos;{0}&apos; will be deleted..
        /// </summary>
        internal static string ChooseBranchesToDeleteText {
            get {
                return ResourceManager.GetString("ChooseBranchesToDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DANGEROUS ACTION!
        ///Branches will be deleted on the remote &apos;{0}&apos;. This can not be undone.
        ///Are you sure you want to continue?.
        /// </summary>
        internal static string DangerousActionText {
            get {
                return ResourceManager.GetString("DangerousActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last activity.
        /// </summary>
        internal static string DateDataGridViewTextBoxColumn {
            get {
                return ResourceManager.GetString("DateDataGridViewTextBoxColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete obsolete branches older than (days).
        /// </summary>
        internal static string DaysOlderThan {
            get {
                return ResourceManager.GetString("DaysOlderThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteCaption {
            get {
                return ResourceManager.GetString("DeleteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete obsolete branches from remote.
        /// </summary>
        internal static string DeleteRemoteBranchesFromFlag {
            get {
                return ResourceManager.GetString("DeleteRemoteBranchesFromFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting branches....
        /// </summary>
        internal static string DeletingBranchesText {
            get {
                return ResourceManager.GetString("DeletingBranchesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting unmerged branches will result in dangling commits. Use with caution!.
        /// </summary>
        internal static string DeletingUnmergedBranchesText {
            get {
                return ResourceManager.GetString("DeletingUnmergedBranchesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete obsolete branches.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete obsolete branches.
        /// </summary>
        internal static string FormText {
            get {
                return ResourceManager.GetString("FormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete remote branches from.
        /// </summary>
        internal static string IncludeRemoteBranches {
            get {
                return ResourceManager.GetString("IncludeRemoteBranches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete unmerged branches.
        /// </summary>
        internal static string IncludeUnmergedBranchesFlag {
            get {
                return ResourceManager.GetString("IncludeUnmergedBranchesFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include unmerged branches.
        /// </summary>
        internal static string IncludeUnmergedBranchesText {
            get {
                return ResourceManager.GetString("IncludeUnmergedBranchesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete branches older than x days.
        /// </summary>
        internal static string Label1Text {
            get {
                return ResourceManager.GetString("Label1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete branches fully merged into branch.
        /// </summary>
        internal static string Label2Text {
            get {
                return ResourceManager.GetString("Label2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch where all branches should be merged in.
        /// </summary>
        internal static string MergedInBranch {
            get {
                return ResourceManager.GetString("MergedInBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last message.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NameDataGridViewTextBoxColumn {
            get {
                return ResourceManager.GetString("NameDataGridViewTextBoxColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &apos;{0}&apos; to search for branches to delete..
        /// </summary>
        internal static string PressToSearchText {
            get {
                return ResourceManager.GetString("PressToSearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search branches.
        /// </summary>
        internal static string RefreshBtn {
            get {
                return ResourceManager.GetString("RefreshBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is regex filter case insensitive?.
        /// </summary>
        internal static string RegexCaseInsensitiveFlag {
            get {
                return ResourceManager.GetString("RegexCaseInsensitiveFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not match.
        /// </summary>
        internal static string RegexDoesNotMatch {
            get {
                return ResourceManager.GetString("RegexDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /(feature|develop)/.
        /// </summary>
        internal static string RegexFilter {
            get {
                return ResourceManager.GetString("RegexFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search branches that does not match regex.
        /// </summary>
        internal static string RegexInvertedFlag {
            get {
                return ResourceManager.GetString("RegexInvertedFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote name obsoleted branches should be deleted from.
        /// </summary>
        internal static string RemoteName {
            get {
                return ResourceManager.GetString("RemoteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search branches.
        /// </summary>
        internal static string SearchBranchesText {
            get {
                return ResourceManager.GetString("SearchBranchesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select branches to delete using checkboxes in &apos;{0}&apos; column..
        /// </summary>
        internal static string SelectBranchesToDeleteText {
            get {
                return ResourceManager.GetString("SelectBranchesToDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case insensitive.
        /// </summary>
        internal static string UseRegexCaseInsensitive {
            get {
                return ResourceManager.GetString("UseRegexCaseInsensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use regex to filter branches.
        /// </summary>
        internal static string UseRegexFilter {
            get {
                return ResourceManager.GetString("UseRegexFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use regex to filter branches to delete.
        /// </summary>
        internal static string UseRegexToFilterBranchesFlag {
            get {
                return ResourceManager.GetString("UseRegexToFilterBranchesFlag", resourceCulture);
            }
        }
    }
}
