namespace GitUI.BranchTreePanel.ContextMenu
{
    /// <summary>
    /// Menu items that can be generated by <see cref="IMenuItemsGenerator{TNode}"/>
    /// </summary>
    public enum MenuItemKey
    {
        // Git Ref Actions
        GitRefCheckout,
        GitRefMerge,
        GitRefRebase,
        GitRefCreateBranch,
        GitRefReset,
        GitRefActionsSeparator,

        // Common Actions
        Rename,
        Delete
    }
}
