// SimpleExt.idl : IDL source for SimpleExt.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (SimpleExt.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
	[
		object,
		uuid(5E2121ED-0300-11D4-8D3B-444553540000),
		dual,
		helpstring("ISimpleShlExt Interface"),
		pointer_default(unique)
	]
	interface ISimpleShlExt : IDispatch
	{
	};

[
	uuid(5E2121E1-0300-11D4-8D3B-444553540000),
	version(1.0),
	helpstring("SimpleExt 1.0 Type Library")
]
library SIMPLEEXTLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(3C16B20A-BA16-4156-916F-0A375ECFFE24),
		helpstring("SimpleShlExt Class")
	]
	coclass SimpleShlExt
	{
		[default] interface ISimpleShlExt;
	};
};
