//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GitUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog
        ///=========
        ///
        ///### [Version 2.51.02] (24 May 2018)
        ///
        ///#### Highlights:
        ///* Simplified installer - Git and KDiff3 installers are no longer installed as part of GitExtensions&apos;s installation. The user will have to install external apps and tools separately.
        ///* Fixes to address a number of layout issues for high DPI monitors.
        ///
        ///#### Features:
        ///* Remove Git and KDiff3 from installer 2.51 - PR [4933]
        ///* Check for recommended Git version 2.51 - PR [4932]
        ///* Check for recommended Git version - PR [4929]
        ///* [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ChangeLog {
            get {
                return ResourceManager.GetString("ChangeLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Henk Westhuis, Arkady Shapkin, Janusz Białobrzewski, RussKie, Steffen Forkmann, Jacob Stanley, Nick Mayer, Kevin Moore, Davide,
        ///Dominique Plante, Grzegorz Pachocki, Seth Behunin, bleis-tift, Chris Meaney, Nathanael Schmied, Adrian Codrington,
        ///Troels Thomsen, Wilbert van Dolleweerd, Tobias Bieniek, Radoslaw Miazio, Stan Angeloff, Matt McCormick,
        ///Bjørn Moe, William Swanson, Daniel Locantore, Harald Deischinger, Radek Miazio, Stefan Rueckl,
        ///Emanuel Henrique do Prado, Lukasz Byczynski, Steffen M. Colding-Jø [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Coders {
            get {
                return ResourceManager.GetString("Coders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andréj Telle, Oliver Friedrich.
        /// </summary>
        internal static string Designers {
            get {
                return ResourceManager.GetString("Designers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon git_extensions_logo_icon {
            get {
                object obj = ResourceManager.GetObject("git_extensions_logo_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 79 collaborators on Transifex website, Gianni Rosa Gallina, Cheng Huang, Floyd Hung, superlongman, rferriz, gor, xaro, bleis-tift, Ralph Haußmann,
        ///Jasper Chien, Arkadiy Shapkin, ferow2k, Thibault D&apos;Archivio, australiensun, Airat Salikhov, Dave Brotherstone,
        ///diegoaossas, hogelog, Philippe Miossec, Michael Benz (Copro), KUNIMI Taiyoh, Victor Shih, bygreencn, mrahn80,
        ///Alexander Eifler, Marcelo Ghelman, ghanique, olshevskiy87.
        /// </summary>
        internal static string Translators {
            get {
                return ResourceManager.GetString("Translators", resourceCulture);
            }
        }
    }
}
