using System.Text;
using System.Text.RegularExpressions;
using System.Xml.Linq;

namespace WinFormsInputParityToAvalonia;

// parity-scaffolding: Generates temporary WinForms-to-Avalonia input metadata for parity verification.
public static partial class InputMetadataGenerator
{
    private static readonly XNamespace XamlNamespace = "http://schemas.microsoft.com/winfx/2006/xaml";

    public static string Generate(string winFormsRoot, string avaloniaRoot)
        => Generate([(winFormsRoot, avaloniaRoot)]);

    public static string Generate(IEnumerable<(string WinFormsRoot, string AvaloniaRoot)> sourceRoots)
    {
        List<ViewMetadata> views = [];
        foreach ((string winFormsRoot, string avaloniaRoot) in sourceRoots)
        {
            string fullWinFormsRoot = Path.GetFullPath(winFormsRoot);
            string fullAvaloniaRoot = Path.GetFullPath(avaloniaRoot);
            if (!Directory.Exists(fullWinFormsRoot) || !Directory.Exists(fullAvaloniaRoot))
            {
                throw new InvalidDataException("Every WinForms/Avalonia source-root pair must exist.");
            }

            foreach (string axamlPath in Directory.EnumerateFiles(fullAvaloniaRoot, "*.axaml", SearchOption.AllDirectories)
                         .Order(StringComparer.Ordinal))
            {
                string relativePath = Path.GetRelativePath(fullAvaloniaRoot, axamlPath);
                string designerPath = Path.Combine(
                    fullWinFormsRoot,
                    Path.ChangeExtension(relativePath, ".Designer.cs"));
                if (!File.Exists(designerPath))
                {
                    continue;
                }

                XDocument axaml = XDocument.Load(axamlPath);
                string className = (string?)axaml.Root?.Attribute(XamlNamespace + "Class")
                    ?? throw new InvalidDataException($"AXAML view '{relativePath}' has no x:Class.");
                HashSet<string> controlNames = axaml.Root!.DescendantsAndSelf()
                    .Select(element => (string?)element.Attribute(XamlNamespace + "Name"))
                    .Where(name => !string.IsNullOrWhiteSpace(name))
                    .ToHashSet(StringComparer.Ordinal)!;
                Dictionary<string, MutableControlMetadata> controls = controlNames.ToDictionary(
                    name => name,
                    _ => new MutableControlMetadata(),
                    StringComparer.Ordinal);

                foreach (string line in File.ReadLines(designerPath))
                {
                    Match match = AssignmentRegex().Match(line);
                    if (!match.Success || !controls.TryGetValue(match.Groups["field"].Value, out MutableControlMetadata? metadata))
                    {
                        continue;
                    }

                    string property = match.Groups["property"].Value;
                    string value = match.Groups["value"].Value.Trim();
                    switch (property)
                    {
                        case "TabIndex":
                            metadata.TabIndex = int.Parse(value, System.Globalization.CultureInfo.InvariantCulture);
                            break;
                        case "TabStop":
                            metadata.IsTabStop = bool.Parse(value);
                            break;
                        case "AccessibleName":
                            metadata.AccessibleName = UnescapeString(value);
                            break;
                    }
                }

                ControlMetadata[] projected = controls
                    .Where(pair => pair.Value.HasValue)
                    .OrderBy(pair => pair.Key, StringComparer.Ordinal)
                    .Select(pair => new ControlMetadata(
                        pair.Key,
                        pair.Value.TabIndex,
                        pair.Value.IsTabStop,
                        pair.Value.AccessibleName))
                    .ToArray();
                if (projected.Length > 0)
                {
                    views.Add(new ViewMetadata(className, projected));
                }
            }
        }

        if (views.Count == 0)
        {
            throw new InvalidDataException("No matching AXAML and WinForms Designer input metadata was found.");
        }

        string[] duplicateClassNames = views
            .GroupBy(view => view.ClassName, StringComparer.Ordinal)
            .Where(group => group.Count() > 1)
            .Select(group => group.Key)
            .ToArray();
        if (duplicateClassNames.Length > 0)
        {
            throw new InvalidDataException($"Duplicate AXAML class metadata: {string.Join(", ", duplicateClassNames)}.");
        }

        StringBuilder builder = new();
        AppendLine("// <auto-generated />");
        AppendLine("// Generated by eng/tools/WinFormsInputParityToAvalonia from matching WinForms Designer files.");
        AppendLine();
        AppendLine("namespace GitUI.Compat;");
        AppendLine();
        AppendLine("// parity-scaffolding: Projects WinForms Designer input metadata until parity verification is removed.");
        AppendLine("internal static class WinFormsInputMetadata");
        AppendLine("{");
        AppendLine("    internal static IReadOnlyDictionary<string, IReadOnlyList<InputControlMetadata>> ByType { get; } =");
        AppendLine("        new Dictionary<string, IReadOnlyList<InputControlMetadata>>(StringComparer.Ordinal)");
        AppendLine("        {");
        foreach (ViewMetadata view in views.OrderBy(view => view.ClassName, StringComparer.Ordinal))
        {
            AppendLine($"            [\"{EscapeString(view.ClassName)}\"] =");
            AppendLine("            [");
            foreach (ControlMetadata control in view.Controls)
            {
                string tabIndex = control.TabIndex?.ToString(System.Globalization.CultureInfo.InvariantCulture) ?? "null";
                string isTabStop = control.IsTabStop?.ToString().ToLowerInvariant() ?? "null";
                string accessibleName = control.AccessibleName is null
                    ? "null"
                    : $"\"{EscapeString(control.AccessibleName)}\"";
                AppendLine($"                new(\"{EscapeString(control.FieldName)}\", {tabIndex}, {isTabStop}, {accessibleName}),");
            }

            AppendLine("            ],");
        }

        AppendLine("        };");
        AppendLine("}");
        return builder.ToString();

        void AppendLine(string value = "")
        {
            builder.Append(value);
            builder.Append('\n');
        }
    }

    private static string UnescapeString(string value)
    {
        if (value.Length < 2 || value[0] != '"' || value[^1] != '"')
        {
            throw new InvalidDataException($"AccessibleName is not a supported string literal: {value}");
        }

        return Regex.Unescape(value[1..^1]);
    }

    private static string EscapeString(string value)
        => value.Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal)
            .Replace("\r", "\\r", StringComparison.Ordinal)
            .Replace("\n", "\\n", StringComparison.Ordinal);

    [GeneratedRegex("^\\s*(?:this\\.)?(?<field>[A-Za-z_][A-Za-z0-9_]*)\\.(?<property>TabIndex|TabStop|AccessibleName)\\s*=\\s*(?<value>.+);\\s*$", RegexOptions.CultureInvariant)]
    private static partial Regex AssignmentRegex();

    private sealed class MutableControlMetadata
    {
        public int? TabIndex { get; set; }

        public bool? IsTabStop { get; set; }

        public string? AccessibleName { get; set; }

        public bool HasValue => TabIndex is not null || IsTabStop is not null || AccessibleName is not null;
    }

    private sealed record ViewMetadata(string ClassName, IReadOnlyList<ControlMetadata> Controls);

    private sealed record ControlMetadata(string FieldName, int? TabIndex, bool? IsTabStop, string? AccessibleName);
}
