name: "Labeler: Build Predictor App"

on:
  # Allow dispatching the workflow via the Actions UI
  workflow_dispatch:
    inputs:
      rebuild:
        description: "Force a rebuild of the app"
        type: boolean

jobs:
  build-predictor:
    permissions:
      actions: write
    uses: dotnet/issue-labeler/.github/workflows/build-predictor.yml@46125e85e6a568dc712f358c39f35317366f5eed # v2.0.0
    with:
      rebuild: ${{ inputs.rebuild }}
